import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class startScreen {
    private JPanel startScreenPanel;
    private JLabel text;
    private Timer flickerTimer;
    private JFrame frame;
    private Login login;
    private boolean loggedIn = false;

    public startScreen() {
        $$$setupUI$$$();
        flickerTimer = new Timer(500, e -> text.setVisible(!text.isVisible()));
        flickerTimer.start();

        startScreenPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (!loggedIn) {
                    login = new Login(frame, frame, frame);
                    login.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosed(WindowEvent e) {
                            if (login.user != null) {
                                loggedIn = true;
                                hideStartScreen();

                            }
                        }
                    });
                }
            }
        });

        startScreenPanel.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (!loggedIn) {
                    login = new Login(frame, frame, frame);
                    login.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosed(WindowEvent e) {
                            if (login.user != null) {
                                loggedIn = true;
                                hideStartScreen();

                            }
                        }
                    });
                }
            }
        });

        startScreenPanel.setFocusable(true);
        startScreenPanel.requestFocusInWindow();

        frame = new JFrame("Start Screen");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(startScreenPanel);
        frame.setSize(1040, 800);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    public void hideStartScreen() {
        frame.setVisible(false);
        frame.dispose();
        frame = null;
    }

    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }

    private void createUIComponents() {
        startScreenPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon backgroundImage = new ImageIcon("C:\\Users\\82106\\IdeaProjects\\VocabBoost\\src\\startScreen.jpg");
                g.drawImage(backgroundImage.getImage(), 0, 0, this.getWidth(), this.getHeight(), this);
            }
        };
    }

    public JPanel getStartScreenPanel() {
        return startScreenPanel;
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            startScreen start = new startScreen();
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        // Layout settings and additional component initialization
        // The actual code is auto-generated by IntelliJ, please do not manually modify.
    }
}
